// OpenAPI 3.1 description of the public read API (served at /v1/openapi.json).
import { PLAYER_STATS, TEAM_STATS } from '../ui/queries.js';

const uuid = { type: 'string', format: 'uuid' };
const season = { name: 'season', in: 'query', required: true, schema: { type: 'integer', minimum: 2000, maximum: 2100 }, description: 'Fall season year, e.g. 2026.' };
const gender = { name: 'gender', in: 'query', schema: { type: 'string', enum: ['m', 'w'] } };
const division = { name: 'division', in: 'query', schema: { type: 'string', enum: ['d1', 'd2', 'd3'] } };
const conference = { name: 'conference', in: 'query', schema: uuid, description: 'college_conferences.id' };
const ok = (description: string) => ({ 200: { description, content: { 'application/json': { schema: { type: 'object' } } } }, 400: { $ref: '#/components/responses/BadRequest' }, 401: { $ref: '#/components/responses/Unauthorized' }, 429: { $ref: '#/components/responses/RateLimited' } });

export function openapiSpec(serverUrl: string): Record<string, unknown> {
  return {
    openapi: '3.1.0',
    info: {
      title: 'Plaibook Stats API',
      version: '1.0.0',
      description: 'Read-only NCAA soccer data (D1/D2/D3, men and women): programs, rosters, players, games, season stats, standings and rankings. Data is crawled from each school\'s athletics site, NCAA.com, conference websites and unitedsoccercoaches.org.\n\n**No API key is required.** Every route answers anonymous requests at the free-tier limit (per client IP, see `limits` in /v1/meta), and keyless responses are readable from any origin. A named key — `Authorization: Bearer <key>` or `X-Api-Key: <key>` — raises the limit and is restricted to the origins configured on the service.',
    },
    servers: [{ url: serverUrl }],
    components: {
      securitySchemes: {
        apiKey: { type: 'http', scheme: 'bearer', description: 'Optional: a named key raises the rate limit.' },
        apiKeyHeader: { type: 'apiKey', in: 'header', name: 'X-Api-Key', description: 'Optional: same key, sent as a header.' },
      },
      responses: {
        BadRequest: { description: 'A parameter is missing or malformed.' },
        Unauthorized: { description: 'A key was sent and it is not valid. Sending no key at all uses the free tier.' },
        RateLimited: { description: 'Request limit exceeded; see Retry-After and X-RateLimit-* headers.' },
      },
    },
    // {} first: no credentials is a supported way to call every route.
    security: [{}, { apiKey: [] }, { apiKeyHeader: [] }],
    paths: {
      '/v1/meta': { get: { summary: 'Seasons, conferences and data freshness', responses: ok('Seasons, current season, divisions, conferences and last successful crawl runs.') } },
      '/v1/status': { get: { summary: 'Crawl health', responses: ok('Recent crawl runs, record-check counts, member programs and games/finals stored.') } },
      '/v1/search': { get: { summary: 'Search programs and players by name', parameters: [{ name: 'q', in: 'query', required: true, schema: { type: 'string', minLength: 2, maxLength: 60 } }, gender, { name: 'limit', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 50 } }], responses: ok('{ q, programs[], players[] } ordered by similarity.') } },
      '/v1/programs': { get: { summary: 'Programs for a season', parameters: [season, gender, division, conference, { name: 'q', in: 'query', schema: { type: 'string' } }, { name: 'members', in: 'query', schema: { type: 'string', enum: ['all'] }, description: 'Include non-NCAA opponents (default: NCAA members only).' }], responses: ok('One row per program with school, conference, membership, computed and official records, sync timestamps and game counts.') } },
      '/v1/programs/{id}': { get: { summary: 'One program with roster, games, standing and rankings', parameters: [{ name: 'id', in: 'path', required: true, schema: uuid }, { ...season, required: false }, { name: 'include', in: 'query', schema: { type: 'string' }, description: 'Comma list of roster,games (default both).' }], responses: ok('program, school, season row, coaches, team stats, standing, conference table, USC poll history, NCAA category ranks, roster (with season stats, school-table stats, splits, honors) and games with team stats.') } },
      '/v1/programs/{id}/roster': { get: { summary: 'Roster with season stats', parameters: [{ name: 'id', in: 'path', required: true, schema: uuid }, season], responses: ok('Players with computed season stats, the school\'s own cumulative stats, splits and honors.') } },
      '/v1/programs/{id}/games': { get: { summary: 'Schedule and results', parameters: [{ name: 'id', in: 'path', required: true, schema: uuid }, season], responses: ok('Games in date order with both sides\' team-stat rows and the truth source.') } },
      '/v1/players/{id}': { get: { summary: 'Player with seasons, career, splits, ranks, honors, game log', parameters: [{ name: 'id', in: 'path', required: true, schema: uuid }], responses: ok('player, seasons[], career, honors[], transfers[], gameLog[].') } },
      '/v1/games/{id}': { get: { summary: 'Box score', parameters: [{ name: 'id', in: 'path', required: true, schema: uuid }, { name: 'include', in: 'query', schema: { type: 'string' }, description: '`raw` adds the source payloads.' }], responses: ok('game header, team stats (both sources), player lines, events, stats { provisional, live_stats_at }. While the match is live the ncaa rows are a snapshot of NCAA.com\'s in-game feed refreshed every couple of minutes (stats.provisional = true) and are replaced by the final box score minutes after full time; the response is cacheable for 15 s then.') } },
      '/v1/leaders': { get: { summary: 'Leaderboards', parameters: [season, gender, division, conference, { name: 'kind', in: 'query', schema: { type: 'string', enum: ['player', 'team'] } }, { name: 'stat', in: 'query', schema: { type: 'string', enum: [...PLAYER_STATS, ...TEAM_STATS] } }, { name: 'min_minutes', in: 'query', schema: { type: 'integer' } }, { name: 'limit', in: 'query', schema: { type: 'integer', maximum: 500, default: 100 } }, { name: 'offset', in: 'query', schema: { type: 'integer', default: 0 } }, { name: 'q', in: 'query', description: 'Player or program name contains', schema: { type: 'string' } }, { name: 'members', in: 'query', schema: { type: 'string', enum: ['all'] } }], responses: ok('{ stats: allowed stat names, stat, rows[], total, limit, offset } — one page sorted by the stat (ascending for goals-against style stats); page with offset until offset + rows.length >= total.') } },
      '/v1/standings': { get: { summary: 'Standings by conference', parameters: [season, gender, division, conference], responses: ok('{ source, official, computed, conferences: [{ conference, source, source_url, rows[] }] }; each row carries checks[] against the official table.') } },
      '/v1/rankings': { get: { summary: 'Polls and NCAA category ranks', parameters: [season, gender, division, { name: 'poll', in: 'query', schema: { type: 'string' }, description: "'usc' (United Soccer Coaches, default) or 'ncaa:<categoryId>'." }, { name: 'week_of', in: 'query', schema: { type: 'string', format: 'date' } }], responses: ok('{ polls[], poll, weeks[], week, rows[] } with rank, previous_rank, first_place_votes, points, record per row.') } },
      '/v1/matches': { get: { summary: 'Matches by day: live, upcoming and finished', parameters: [{ name: 'date', in: 'query', schema: { type: 'string', format: 'date' }, description: 'Eastern date; defaults to today' }, { name: 'days', in: 'query', schema: { type: 'integer', minimum: 1, maximum: 7, default: 1 } }, gender, division, conference, { name: 'status', in: 'query', schema: { type: 'string', enum: ['scheduled', 'live', 'final', 'postponed', 'cancelled'] } }, { name: 'only', in: 'query', schema: { type: 'string', enum: ['conf', 'ranked'] }, description: 'conference games only, or games with a ranked team' }], responses: ok('{ from, to, season, live, games[], generated_at }. Games are ordered live first, then by kickoff (start_epoch, unix seconds). Each game has home/away { program_id, name, short_name, seo, logo, conference, division, rank (latest coaches poll), score }, live { period, clock, updated_at } while in play, venue { name, city } (the ground and "City, ST" from the schools\' schedules or the box score), weather (National Weather Service hourly forecast for the ground at kickoff: temp_f, wind_mph, wind_gust_mph, wind_dir, precip_pct, humidity, short, is_day, place, for, read_at, time_assumed; refreshed every 3 hours, hourly in the last 6 hours, kept after kickoff), result_pending (the day is over and no result is in), kickoff_tbd, flags (neutral_site, conference_game, postseason, forfeit, overtime, shootout). Scores refresh every minute during games; responses with a live game are cached for 15 s.') } },
      '/v1/matches/{id}/preview': { get: { summary: 'Match preview and review: head-to-head, form, standing, poll rank, key players, lineups', parameters: [{ name: 'id', in: 'path', required: true, schema: uuid }], responses: ok('{ game, head_to_head { played, home_wins, away_wins, ties, home_goals, away_goals, avg_goals, home_clean_sheets, away_clean_sheets, at_home, at_away, at_neutral { w, l, t }, biggest_home_win, biggest_away_win { id, game_date, score, margin }, streak { side, kind: won|unbeaten|drawn, count }, first_season, last_meeting, games[] (every earlier meeting, newest first, each with result W/L/T for the current home team and scorers[] { program_id, name, minute }) } — all from the current home team\'s side, sides { home, away } } — each side: stats (team season stats; form.last5 oldest→newest, streak), standing (rank, pod, conf record, points, of = table size), poll { rank, week_of }, leaders { scorers[], assists[], keeper }, lineup_status (match: this match\'s box score names starters · no_starters: its box score only lists who played · past: no box score yet · none), lineup { source, starters[], subs[], dnp[], keeper } for this match only (null until its box score exists), last_lineup { …, game_id, game_date, opponent } the side\'s latest lineup with starters when lineup is null; each line carries headshot_url where the school publishes a hotlinkable photo. Suppressed players are withheld (numbers stay, names and ids go).') } },
      '/v1/conferences': { get: { summary: 'Conferences with member counts and the top of each table', parameters: [season, gender, division], responses: ok('{ season, conferences: [{ id, ncaa_seo, name, short_name, division, site_host, members { m, w }, table { m|w: { top: [{ program_id, name, seo, logo, rank, conf_w, conf_l, conf_t, conf_pts }], source: conference|computed|none } } }] } sorted by name.') } },
      '/v1/conferences/{id}': { get: { summary: 'One conference: table, members, this week\'s matches, leaders, ranked members', parameters: [{ name: 'id', in: 'path', required: true, schema: uuid }, season, { ...gender, description: 'm (default) or w' }], responses: ok('{ conference, season, gender, standings (as /v1/standings for one conference), members[] (with season stats, form and poll rank), this_week (as /v1/matches, Monday to Sunday Eastern), leaders { points[], goals[], assists[], save_pct[] }, ranked[] }.') } },
      '/v1/openapi.json': { get: { summary: 'This document', security: [], responses: { 200: { description: 'OpenAPI 3.1' } } } },
    },
  };
}
