// What each job does and which parameters it takes, so the console can draw a form per job instead of a JSON
// box. Kept in one place next to the schedule rather than spread over the job modules; tests/jobs/catalogue.test.ts
// checks every registered job is described here.
import type { JobMeta, ParamSpec } from './runner.js';

const season: ParamSpec = { name: 'season', type: 'number', label: 'Season', help: 'Defaults to the current season.' };
const gender: ParamSpec = { name: 'gender', type: 'enum', label: 'Gender', options: ['m', 'w'], help: 'Both when blank.' };
const division: ParamSpec = { name: 'division', type: 'enum', label: 'Division', options: ['d1', 'd2', 'd3'], help: 'All when blank.' };
const program: ParamSpec = { name: 'program', type: 'string', label: 'Program (school slug)', help: 'One school, e.g. duke.' };
const force: ParamSpec = { name: 'force', type: 'boolean', label: 'Force', help: 'Ignore freshness and re-fetch.' };
const STAGES = ['roster', 'schedule', 'stats', 'boxscores', 'bios'];

export const JOB_META: Record<string, JobMeta> = {
  'discover-teams': { description: 'Find every program from the NCAA.com scoreboard and school pages; creates programs and program-seasons.', lane: 'crawl', params: [season, gender, division, program, force, { name: 'skip_school_pages', type: 'boolean', label: 'Skip school pages' }], dangerous: true },
  'detect-sites': { description: 'Work out which platform (Sidearm, Presto, WMT) each school\'s athletics site runs.', lane: 'crawl', params: [season, program, force, { name: 'only_unknown', type: 'boolean', label: 'Only unclassified schools' }, { name: 'platforms', type: 'string[]', label: 'Re-probe platforms', help: 'e.g. unknown, other' }, { name: 'program_status', type: 'string[]', label: 'Only site statuses', help: 'unknown, failed, not_found' }] },
  'sweep-scoreboard': { description: 'Read the NCAA.com scoreboard for each day and division: creates fixtures, links contest ids, records finals.', lane: 'crawl', params: [season, gender, division, { name: 'days', type: 'enum', label: 'Days', options: ['recent', 'all'], default: 'recent', help: 'recent = yesterday, today, tomorrow.' }, force] },
  'fetch-games-ncaa': { description: 'Fetch NCAA.com box scores and play-by-play for finished games with a contest id.', lane: 'crawl', params: [season, gender, division, program, { name: 'recent_days', type: 'number', label: 'Recent days', help: 'Only games in the last N days.' }, { name: 'refetch', type: 'boolean', label: 'Re-fetch already fetched' }, { name: 'limit', type: 'number', label: 'Limit' }, { name: 'contest_ids', type: 'string[]', label: 'Contest ids' }] },
  'sync-site': { description: 'Crawl school athletics sites: roster, schedule, cumulative stats, box scores, player bios.', lane: 'crawl', params: [season, program, gender, division, { name: 'stages', type: 'string[]', label: 'Stages', options: STAGES, help: 'All five when blank.' }, { name: 'only_recent_days', type: 'number', label: 'Only programs that played in the last N days' }, { name: 'only_pending_boxscores', type: 'number', label: 'Only programs with a box score missing (days)' }, { name: 'only_never_synced', type: 'boolean', label: 'Only never-synced rosters' }, force, { name: 'reparse', type: 'boolean', label: 'Re-parse stored pages', help: 'Box scores from the fetch cache, no new requests.' }, { name: 'from_cache', type: 'boolean', label: 'Use pages from the last 14 days', help: 'Fetch only what was never downloaded.' }], dangerous: true },
  'reconcile-games': { description: 'Pick each final\'s source of truth (school box score when valid, else NCAA.com) and repair swapped sides.', lane: 'crawl', params: [season, program, { name: 'all', type: 'boolean', label: 'Every final', help: 'Not just recently fetched ones.' }] },
  'compute-aggregates': { description: 'Recompute season totals per player and team from the box scores (and transfer links).', lane: 'crawl', params: [season, program, gender, { name: 'transfers', type: 'boolean', label: 'Link transfers', default: false }] },
  'refresh-rankings': { description: 'Read the United Soccer Coaches polls and NCAA.com category ranks.', lane: 'crawl', params: [season, gender, division, { name: 'categories', type: 'boolean', label: 'NCAA category ranks', default: true, help: 'Off = polls only (fast).' }] },
  'verify-membership': { description: 'Check conference membership and NCAA-listed records against NCAA.com\'s leaderboard.', lane: 'crawl', params: [season, gender, division] },
  'compute-standings': { description: 'Read conference standings pages and compute our own tables; records the differences.', lane: 'crawl', params: [season, gender, division, { name: 'conference', type: 'string', label: 'Conference (NCAA seo)', help: 'One conference only.' }] },
  'resolve-orphans': { description: 'Link box-score-only players and unresolved opponents to programs and rosters.', lane: 'crawl', params: [season] },
  'live': { description: 'Live scores and live stats from NCAA.com while games are in progress (runs every minute in game hours).', lane: 'live', params: [season, { name: 'dates', type: 'string[]', label: 'Dates (Eastern)', help: 'YYYY-MM-DD; today when blank.' }, force, { name: 'detail', type: 'boolean', label: 'Live stats phase', default: true }] },
  'pq-health': { description: 'Check the NCAA.com persisted GraphQL queries still work; re-learns the hashes if not.', lane: 'crawl', params: [] },
  'quality': { description: 'Run the data-quality checks for a season and store a snapshot the console can trend.', lane: 'crawl', params: [season] },
  'weather': { description: 'Weather at kickoff for the next week of matches: the ground\'s city (schedules, else the home team\'s usual city) and the National Weather Service hourly forecast.', lane: 'aux', params: [season, { name: 'days', type: 'number', label: 'Days ahead', default: 6, help: 'NWS forecasts reach about 6.5 days.' }, { name: 'force', type: 'boolean', label: 'Re-read every game', help: 'Ignore the 3-hour refresh rule.' }] },
  'h2h-detail': { description: 'NCAA.com box scores for earlier meetings a match page asked for (queued automatically for head-to-head scorers).', lane: 'aux', params: [season, { name: 'contest_ids', type: 'string[]', label: 'Contest ids' }] },
  'merge-twins': { description: 'Fold synthetic x- programs into the real program of the same school (duplicate standings rows, unmatched poll entries). Lists the pairs unless Apply is set.', lane: 'crawl', params: [season, { name: 'apply', type: 'boolean', label: 'Apply', help: 'Off = list the pairs only.' }, { name: 'only', type: 'string[]', label: 'Only these x- slugs' }], dangerous: true },
  'final-detail': { description: 'A game that just went final: its NCAA.com box score now, its two programs reconciled and totals recomputed, then Plaibook told (queued by the live job; runs on the side lane).', lane: 'aux', params: [season, { name: 'contest_ids', type: 'string[]', label: 'Contest ids' }] },
  'ops-retention': { description: 'Delete finished runs older than 30 days (live: 1 day), API usage older than 90 days, quality snapshots older than 180 days.', lane: 'crawl', params: [] },
  // Plaibook Stats Pro (API-Football; every request counts against Plaibook's shared daily quota, see src/sources/apiFootball/client.ts).
  'pro-catalog': { description: 'Pro: the competition list from API-Football (1 request): leagues, seasons and coverage. New professional leagues switch on by themselves.', lane: 'pro-bulk', params: [] },
  'pro-scoreboard': { description: 'Pro: every match worldwide on a UTC day (1 request per day) for enabled competitions; finals queue their detail.', lane: 'pro', params: [{ name: 'days', type: 'enum', label: 'Days', options: ['auto', 'today', 'recent'], default: 'auto', help: 'recent = yesterday, today, tomorrow; auto = recent at the top of the hour.' }, { name: 'dates', type: 'string[]', label: 'Dates (UTC)', help: 'YYYY-MM-DD; overrides Days.' }] },
  'pro-live': { description: 'Pro: live scores for every match in play (1 request); a match that leaves the live list is read by id for its final score and detail.', lane: 'pro', params: [] },
  'pro-final-detail': { description: 'Pro: events, lineups, player and team stats for finals missing them (20 matches per request), then season totals.', lane: 'pro', params: [{ name: 'ids', type: 'string[]', label: 'Fixture ids' }, { name: 'limit', type: 'number', label: 'Limit', default: 400 }, { name: 'since_days', type: 'number', label: 'Finals from the last N days', default: 7 }] },
  'pro-standings': { description: 'Pro: league tables for every league season with a new final (1 request each), or one on demand.', lane: 'pro', params: [{ name: 'league', type: 'number', label: 'League id' }, { name: 'season', type: 'number', label: 'Season (provider year)' }] },
  'pro-backfill': { description: 'Pro: history a league season at a time (fixtures, clubs, detail, table, totals), current seasons first by priority, on the backfill quota floor.', lane: 'pro-bulk', params: [{ name: 'league', type: 'number', label: 'Only this league id' }, { name: 'seasons', type: 'number', label: 'Seasons back', help: 'Defaults to PRO_BACKFILL_SEASONS.' }, { name: 'max_minutes', type: 'number', label: 'Time budget (minutes)', default: 50 }], dangerous: true },
  'pro-players': { description: 'Pro: player profiles (full name, birth date, height, photo) for players first seen in a match (1 request each).', lane: 'pro-bulk', params: [{ name: 'limit', type: 'number', label: 'Players', default: 60 }] },
  'pro-college-link': { description: 'Pro: which pro players played NCAA soccer, from Wikidata and our own rosters (no API-Football requests).', lane: 'pro-bulk', params: [] },
  'pro-plan': { description: 'Pro: decides what the crawl holds (every club, player, squad, season total, match detail, transfer, coach, injury, trophy) as tasks in pro_crawl_tasks. No API requests.', lane: 'pro-bulk', params: [] },
  'pro-crawl': { description: 'Pro: works through the crawl tasks in priority order on the backfill quota floor, a time budget at a time; backs off when the database is slow.', lane: 'pro-bulk', params: [{ name: 'max_minutes', type: 'number', label: 'Time budget (minutes)', default: 9 }, { name: 'max_calls', type: 'number', label: 'At most N requests' }, { name: 'kinds', type: 'string[]', label: 'Only these kinds', help: 'e.g. squad, league_players' }] },
  'pro-rank': { description: 'Pro: nightly recent minutes (search order), indexable, current club and shirt number for every player.', lane: 'pro-bulk', params: [] },
  'asa-sync': { description: 'Sources: American Soccer Analysis for MLS, NWSL, USL Championship, League One, MLS Next Pro and Super League: games, xG, shooting, passing, goals added, clubs, players, grounds (no API-Football requests).', lane: 'sources', params: [{ name: 'league', type: 'number', label: 'API-Football league id', help: 'e.g. 253 for MLS. All six when blank.' }, season, { name: 'history', type: 'boolean', label: 'Past seasons too', default: true }, { name: 'max_minutes', type: 'number', label: 'Time budget (minutes)', default: 9 }] },
  'asa-shots': { description: 'Sources: every shot of each final game from American Soccer Analysis (one request a game), newest seasons first.', lane: 'sources', params: [{ name: 'league', type: 'number', label: 'API-Football league id' }, { name: 'max_minutes', type: 'number', label: 'Time budget (minutes)', default: 9 }] },
  'source-map': { description: 'Sources: match other sources\' clubs, games and players to API-Football (by name, games played, birth date and club). Hand-verified rows are kept.', lane: 'sources', params: [{ name: 'league', type: 'number', label: 'API-Football league id' }] },
  'source-check': { description: 'Sources: compare each collected score, minute total, goal and assist with API-Football and record agree / differ / unmatched.', lane: 'sources', params: [{ name: 'league', type: 'number', label: 'API-Football league id' }, season] },
  'openfootball-sync': { description: 'Sources: MLS results from openfootball (public domain) for every season it has, 2005 on; matched and checked against API-Football like the others.', lane: 'sources', params: [{ name: 'from', type: 'number', label: 'From season', default: 2005 }, { name: 'to', type: 'number', label: 'To season' }] },
  'history-fill': { description: 'Sources: seasons API-Football does not have (MLS 2005-2011 from openfootball, NWSL 2016-2018 from American Soccer Analysis), with a table from the results; only while the source agrees with API-Football on 99%+ of scores.', lane: 'sources', params: [{ name: 'source', type: 'string', label: 'Source', help: 'openfootball or asa' }, { name: 'league', type: 'number', label: 'API-Football league id' }] },
  'wikipedia-sync': { description: 'Sources: league tables from Wikipedia season articles (CC BY-SA, credited) for MLS from 1996, NWSL from 2013 and USL from 2011; finished seasons once.', lane: 'sources', params: [{ name: 'league', type: 'number', label: 'API-Football league id' }, season, { name: 'force', type: 'boolean', label: 'Read again' }] },
  'results-tables': { description: 'Sources: league tables worked out from API-Football results where no source has one (WPSL and others), one per group of clubs that played each other. No API requests.', lane: 'sources', params: [{ name: 'league', type: 'number', label: 'API-Football league id' }] },
  'hourly': { description: 'Every 30 minutes in season: recent scoreboard days, NCAA box scores, pending school box scores, reconcile, aggregates.', lane: 'crawl', composite: true, params: [season] },
  'nightly': { description: 'Daily: two-day sweep, NCAA re-fetch, school sync (no bios), orphans, reconcile, aggregates, standings, polls, quality, retention.', lane: 'crawl', composite: true, params: [season], dangerous: true },
  'standings': { description: 'Every 3 hours in season: membership verification, conference standings, polls.', lane: 'crawl', composite: true, params: [season] },
  'weekly': { description: 'Tuesdays: discover teams, verify membership, detect sites, rankings with categories, every schedule and box score, full sweep, orphans, reconcile all.', lane: 'crawl', composite: true, params: [season], dangerous: true },
  'backfill': { description: 'Everything for a season from scratch (hours).', lane: 'crawl', composite: true, params: [season, gender, division, force], dangerous: true },
  'sync-program': { description: 'One program end to end: site sync, NCAA box scores, reconcile, aggregates.', lane: 'crawl', composite: true, params: [season, program, gender, force, { name: 'conference', type: 'string', label: 'Conference (NCAA seo)' }] },
};

/** The jobs the 'pro' worker lane claims (and the crawl lane leaves alone). */
export const PRO_LANE_JOBS = Object.entries(JOB_META).filter(([, m]) => m.lane === 'pro').map(([n]) => n);
/** The jobs the 'sources' lane claims: other data sources and the checks against API-Football. */
export const SOURCE_JOBS = Object.entries(JOB_META).filter(([, m]) => m.lane === 'sources').map(([n]) => n);
/** The jobs the 'pro-bulk' lane claims: the long crawl work, kept off both the college crawl and the pro scoreboard. */
export const PRO_BULK_JOBS = Object.entries(JOB_META).filter(([, m]) => m.lane === 'pro-bulk').map(([n]) => n);

export function metaFor(name: string): JobMeta {
  return JOB_META[name] ?? { description: '', lane: 'crawl', params: [] };
}
